D25 13 fix
OneYearFourCut/OneYearFourCut pull request #15
Opened 2022-12-29 05:19 UTC by Inside-eun

![image](https://user-images.githubusercontent.com/103915161/209906552-0b1eef6b-6230-44fd-8016-822a93738ade.png)

CSS 일부 수정, 
대댓글 페이지 구현

**추후 답글과 덧글 구별 CSS 추가 예정**
**대댓글 작성은 잠시 오류가 있어 막아두었습니다 추가 예정** 

덧글 삭제 로직이 현재 오류가 있습니다. 
덧글 삭제 이슈 해결, 덧글 입력하여 정보가 바뀌었을때는 무한스크롤 재 렌더링하여 새로 입력된 덧글까지 refetch하는 것 두 가지 문제 해결법 아시면 코멘트 부탁합니다.

2022-12-29 06:02 UTC, dorrion approved these changes
고생하셨습니다

2022-12-29 06:02 UTC, dorrion commented on client/src/SingleComments/hooks/useDeleteComment.tsx
> +        //조언부탁드립니다
지금 삭제가 이뤄지지 않고 있는건가용~?

2022-12-29 06:36 UTC, Inside-eun commented on client/src/SingleComments/hooks/useDeleteComment.tsx
> +        //조언부탁드립니다
넵 맞아요 삭제가 안되는 상태로 만들어뒀어요

2022-12-29 06:58 UTC, kkdy21 requested changes

2022-12-29 06:58 UTC, kkdy21 commented on client/src/store/types.ts
> +import { LargeNumberLike } from 'crypto';
이거는 안쓰시는거면 삭제해주세요~

2023-01-04 02:38 UTC, kkdy21 approved these changes

2023-01-04 02:40 UTC, merged